### ISSUE TITLE
Scoped scss doesn't work

### ISSUE THREAD

**Issue by ppsirius** [visualfanatic/vue-svg-loader#57]
Example code:
```html
<style scoped lang="scss">
.svg-dashboard {
  &.active {
    path {
      fill: #f4a660;
    }
  }
}
```

Output:
```css
.svg-dashboard.active path[data-v-f20d224e] {
  fill: #f4a660;
}
```

Scoped css is generating but data attribute doesn't add to path inside svg. When I paste svg code inline without loader, scoped attribute is added.
